Problem: Calculate the percentage of calories from carb/ protein /fat for each food.

      Apple    Beef     Eggs    Tomatoes

Carb    56.0   0.0      4.4     68.0

Protein 1.2    104.0    52.0    8.0

Fat     1.8    135.0    99.0    0.9





In [13]:
#Calculate the percentage of calories for each food.
import numpy as np
A = np.array([[56.0,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]])
print(A)
Cal= A.sum(axis=0) # axis=0 sum vertically whereas axis=1 sum horizentally
print(Cal)
Total_cal_percentage= 100*A/Cal.reshape(1,4)# reshape redundant here,just make sure shape is correct
print(Total_cal_percentage)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]
[ 59.  239.  155.4  76.9]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
