1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Print the numpy version and the configuration

In [ ]:
print(np.__version__)
np.show_config()

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


3. Create a null vector of size 10

In [ ]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4.How to get the documentation of the numpy add function from the command
line? 

In [ ]:
python -c "import numpy; numpy.info(numpy.add)"

5.Create a null vector of size 10 but the fifth value which is 1. 

In [ ]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


6. Create a vector with values ranging from 10 to 49

In [ ]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


7. Reverse a vector (first element becomes last)

In [ ]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


8. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


9. Find indices of nonzero elements from [1,2,0,0,4,0]

In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


10. Create a 3x3 identity matrix

In [ ]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11. Create a 3x3x3 array with random values

In [ ]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.91945259 0.76640558 0.57450306]
  [0.79252995 0.07295508 0.12061391]
  [0.41790873 0.06746949 0.50273255]]

 [[0.45009144 0.31350941 0.83386619]
  [0.94145007 0.96183042 0.87262028]
  [0.84382745 0.80577258 0.83699211]]

 [[0.46342866 0.05182751 0.72946246]
  [0.72432674 0.39422379 0.72111553]
  [0.26751666 0.3363121  0.76179359]]]


12. Create a 10x10 array with random values and find the minimum and maximum
values 

In [ ]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.001930224590477203 0.9906168712242509


13. Create a random vector of size 30 and find the mean value

In [ ]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5680909152803848


14.Create a 2d array with 1 on the border and 0 inside

In [ ]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


15. What is the result of the following expression?

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

16. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


17. Create a 8x8 matrix and fill it with a checkerboard pattern.

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


19.Create a checkerboard 8x8 matrix using the tile function

In [ ]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Normalize a 5x5 random matrix

In [ ]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.98609875 0.01632923 0.65596916 0.98266428 0.47555599]
 [0.833866   0.34825134 0.63748302 0.8685288  0.60948097]
 [0.08463131 0.57588999 0.01063565 0.         0.56681534]
 [0.21953193 0.43968479 0.01008981 0.12977138 0.31030386]
 [0.20095931 1.         0.19705971 0.65902384 0.53553053]]


21. Create a custom dtype that describes a color as four unisgned bytes (RGBA)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
("g", np.ubyte, 1),
("b", np.ubyte, 1),
("a", np.ubyte, 1)])


22. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [ ]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


23. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [ ]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


24. What is the output of the following script?

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


25.How to round away from zero a float array ?

In [ ]:
Z = np.random.uniform(-10,+10,10)
print (np.trunc(Z + np.copysign(0.5, Z)))

[ -9.  -1.   7.  -9.  -8.   3. -10.   1.   9.  10.]


26. Extract the integer part of a random array using 5 different methods

In [ ]:
Z = np.random.uniform(0,10,10)
print(Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[4.62353709 8.40759173 5.6851733  0.69024903 3.94604569 5.33090968
 1.73825725 6.58246474 8.24863867 5.66423116]
[4. 8. 5. 0. 3. 5. 1. 6. 8. 5.]
[4. 8. 5. 0. 3. 5. 1. 6. 8. 5.]
[4. 8. 5. 0. 3. 5. 1. 6. 8. 5.]
[4 8 5 0 3 5 1 6 8 5]
[4. 8. 5. 0. 3. 5. 1. 6. 8. 5.]


27. Create a 5x5 matrix with row values ranging from 0 to 4

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


28. Consider a generator function that generates 10 integers and use it to build an array

In [ ]:
def generate():
  for x in xrange(10):
    yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

29. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [ ]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


30. Create a random vector of size 10 and sort it

In [ ]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.10640872 0.1140425  0.18588281 0.23175468 0.44820954 0.62076519
 0.66961208 0.7646244  0.80550194 0.89012715]


31. How to sum a small array faster than np.sum?

In [ ]:
Z = np.arange(10)
np.add.reduce(Z)

45

32.Consider two random array A anb B, check if they are equal

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)
equal = np.allclose(A,B)
print(equal)

[0 0 1 1 0]
[1 1 1 1 0]
False


33. Make an array immutable (readonly)

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: ignored

34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.2215477  1.00956054 0.23809987 1.13586085 0.83963682 0.73072187
 0.46613162 0.82561635 0.74619429 0.29504355]
[0.8541187  0.73546613 0.55968908 0.7021983  0.57910936 1.05852051
 1.22275891 0.69485696 0.95519881 0.80192721]


35.Create random vector of size 10 and replace the maximum value by 0

In [ ]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.5390677  0.56277853 0.12142089 0.20674682 0.82957212 0.53736899
 0.96249571 0.89898419 0.49668806 0.93883187]
[0.5390677  0.56277853 0.12142089 0.20674682 0.82957212 0.53736899
 0.         0.89898419 0.49668806 0.93883187]


36.Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [ ]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

37.Given two arrays, X and Y, construct the Cauchy matrix C (Cij = 1/(xi yj))

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


38. Print the minimum and maximum representable value for each numpy scalar type

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


39. How to find the closest value (to a given scalar) in an array?

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

98


40. Create a structured array representing a position (x,y) and a color (r,g,b)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
('y', float, 1)]),
('color', [ ('r', float, 1),
('g', float, 1),
('b', float, 1)])])
print(Z)

41. Consider a random vector with shape (100,2) representing coordinates, find point by point distances.

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.81533626 0.50401431 0.65926148 0.78221748 0.37027687
  0.73393948 0.18525956 0.88747464 0.39920515]
 [0.81533626 0.         0.31418204 0.47815957 0.53627357 0.65633866
  0.15305411 0.67155637 0.45427957 0.47785322]
 [0.50401431 0.31418204 0.         0.42101249 0.47222161 0.37791265
  0.27015657 0.37727987 0.4930188  0.18762774]
 [0.65926148 0.47815957 0.42101249 0.         0.8835617  0.7446779
  0.3251255  0.47405104 0.86903146 0.57285338]
 [0.78221748 0.53627357 0.47222161 0.8835617  0.         0.42936626
  0.6275192  0.75235386 0.16323175 0.41123908]
 [0.37027687 0.65633866 0.37791265 0.7446779  0.42936626 0.
  0.6465274  0.40487086 0.55968479 0.19029304]
 [0.73393948 0.15305411 0.27015657 0.3251255  0.6275192  0.6465274
  0.         0.57173545 0.57535056 0.45680051]
 [0.18525956 0.67155637 0.37727987 0.47405104 0.75235386 0.40487086
  0.57173545 0.         0.82754582 0.34133024]
 [0.88747464 0.45427957 0.4930188  0.86903146 0.16323175 0.55968479
  0.57535056 0.8275458

42. What is the equivalent of enumerate for numpy arrays?

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
  print(index, value)
for index in np.ndindex(Z.shape):
  print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


43. Generate a generic 2D Gaussianlike array

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

44. How to randomly place p elements in a 2D array?

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


45.Subtract the mean of each row of a matrix

In [ ]:
X = np.random.rand(5, 10)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)
# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[-0.07196194 -0.34755706  0.25402262  0.13440998 -0.17362261 -0.09135304
   0.00770844  0.23182701 -0.33709458  0.39362118]
 [-0.05984859  0.32460578  0.11204361 -0.31275336  0.15553857  0.03261423
  -0.33362484  0.03589201 -0.34396054  0.38949313]
 [-0.14054623 -0.05215521  0.25669357  0.12119244 -0.16926798 -0.25328737
   0.38884609 -0.35736996 -0.13545045  0.34134509]
 [-0.4049578  -0.00303527  0.19274878 -0.02398775 -0.3188344  -0.40718884
   0.3402728   0.33061464  0.03072997  0.26363787]
 [ 0.30818901  0.31420554 -0.4274055  -0.11156769  0.13161522 -0.23857052
   0.11371472 -0.17969028  0.40803656 -0.31852707]]
[[-0.07196194 -0.34755706  0.25402262  0.13440998 -0.17362261 -0.09135304
   0.00770844  0.23182701 -0.33709458  0.39362118]
 [-0.05984859  0.32460578  0.11204361 -0.31275336  0.15553857  0.03261423
  -0.33362484  0.03589201 -0.34396054  0.38949313]
 [-0.14054623 -0.05215521  0.25669357  0.12119244 -0.16926798 -0.25328737
   0.38884609 -0.35736996 -0.13545045  0.34134509]

46. How to I sort an array by the nth column?

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[3 3 0]
 [5 5 3]
 [0 4 4]]
[[3 3 0]
 [0 4 4]
 [5 5 3]]


47. How to tell if a given 2D array has null columns?

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


48. Find the nearest value from a given value in an array

In [ ]:
Z = np.random.uniform(0,1,10)
print(Z)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

[0.11314308 0.69799003 0.46039798 0.17748945 0.34267689 0.1406482
 0.99934374 0.76907903 0.69321287 0.34837261]
0.46039798246357433


49.Consider a given vector, how to add 1 to each element indexed by a second
vector (be careful with repeated indices)?

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 5. 4. 4. 2. 4. 3. 1. 2. 3.]


50. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


51. Considering a four dimensions array, how to get sum over the last two axis at once?

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
print (A)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[[[5 7 1 9]
   [1 0 5 1]
   [9 5 2 2]]

  [[8 0 3 9]
   [4 1 8 9]
   [7 0 9 6]]

  [[1 5 3 3]
   [5 8 8 3]
   [3 2 5 7]]

  [[6 6 8 6]
   [4 4 8 3]
   [7 5 7 0]]]


 [[[6 5 4 5]
   [0 2 2 8]
   [9 9 9 3]]

  [[9 3 4 6]
   [2 9 2 2]
   [1 4 7 9]]

  [[3 8 6 6]
   [6 6 4 0]
   [5 1 6 7]]

  [[0 7 8 9]
   [2 7 2 6]
   [6 6 6 2]]]


 [[[8 0 0 9]
   [0 8 2 0]
   [7 1 6 7]]

  [[3 5 0 1]
   [9 3 7 3]
   [8 4 8 7]]

  [[4 7 5 8]
   [7 6 2 6]
   [0 1 7 4]]

  [[1 4 3 3]
   [8 1 2 0]
   [7 6 3 9]]]]
[[47 64 53 64]
 [62 58 58 61]
 [48 58 57 47]]


52. Considering a onedimensional vector D, how to compute means of subsets of D
using a vector S of same size describing subset indices?

In [ ]:
D = np.random.uniform(0,1,100)
#print(D)
S = np.random.randint(0,10,100)
#print(S)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.42156071 0.60600274 0.40256798 0.57880046 0.54789501 0.61282077
 0.40468054 0.53270213 0.50479161 0.59552341]


53. How to get the diagonal of a dot product?

In [ ]:
# Slow version
A = np.arange(12).reshape((4,3))
B= np.arange(6).reshape(3,2)

np.diag(np.dot(A, B))
# Fast version
#np.sum(A * B.T, axis=1)
# Faster version
#np.einsum("ij,ji->i", A, B)

array([10, 40])

54. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


55. Consider an array of dimension (5,5,3), how to mulitply it by an array with
dimensions (5,5)?

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


56. How to swap two rows of an array?

In [ ]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


57. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 6, 11) ( 6, 99) ( 9, 47) ( 9, 80) (11, 99) (13, 69) (13, 70) (15, 59)
 (15, 60) (18, 66) (18, 90) (21, 38) (21, 43) (21, 45) (21, 83) (35, 76)
 (35, 82) (38, 43) (41, 65) (41, 73) (45, 83) (47, 80) (59, 60) (65, 67)
 (65, 73) (66, 90) (67, 67) (69, 70) (76, 82)]


58. Given an array C that is a bincount, how to produce an array A such that
np.bincount(A) == C?

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


59. How to compute averages using a sliding window over an array?

In [ ]:
def moving_average(a, n=3) :
  ret = np.cumsum(a, dtype=float)
  ret[n:] = ret[n:] - ret[:-n]
  return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


60. Consider a onedimensional
array Z, build a twodimensional
array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[3], Z[2],Z[1])

In [ ]:
from numpy.lib import stride_tricks
def rolling(a, window):
  shape = (a.size - window + 1, window)
  strides = (a.itemsize, a.itemsize)
  return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


61. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to
compute distance from p to each line i (P0[i],P1[i])?

In [ ]:
def distance(P0, P1, p):
  T = P1 - P0
  L = (T**2).sum(axis=1)
  U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
  U = U.reshape(len(U),1)
  D = P0 + U*T - p
  return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[8.45715383 2.72181849 0.25998477 8.93124544 6.86569842 3.15438713
 7.03644556 4.93658612 8.71126516 7.04407866]


62. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
A = np.array([distance(P0,P1,p_i) for p_i in p])
print(A)

63. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an
array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [ ]:
Z = np.arange(1,15,dtype=uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

64. Compute a matrix rank

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


65. How to find the most frequent value in an array?

In [ ]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

5


66. Extract all the contiguous 3x3 blocks from a random 10x10 matrix 

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 0 1]
   [2 2 4]
   [0 1 2]]

  [[0 1 3]
   [2 4 2]
   [1 2 0]]

  [[1 3 1]
   [4 2 0]
   [2 0 2]]

  [[3 1 2]
   [2 0 3]
   [0 2 4]]

  [[1 2 1]
   [0 3 1]
   [2 4 4]]

  [[2 1 0]
   [3 1 2]
   [4 4 2]]

  [[1 0 3]
   [1 2 1]
   [4 2 4]]

  [[0 3 3]
   [2 1 4]
   [2 4 3]]]


 [[[2 2 4]
   [0 1 2]
   [2 1 0]]

  [[2 4 2]
   [1 2 0]
   [1 0 1]]

  [[4 2 0]
   [2 0 2]
   [0 1 0]]

  [[2 0 3]
   [0 2 4]
   [1 0 2]]

  [[0 3 1]
   [2 4 4]
   [0 2 2]]

  [[3 1 2]
   [4 4 2]
   [2 2 1]]

  [[1 2 1]
   [4 2 4]
   [2 1 0]]

  [[2 1 4]
   [2 4 3]
   [1 0 0]]]


 [[[0 1 2]
   [2 1 0]
   [3 3 1]]

  [[1 2 0]
   [1 0 1]
   [3 1 0]]

  [[2 0 2]
   [0 1 0]
   [1 0 3]]

  [[0 2 4]
   [1 0 2]
   [0 3 0]]

  [[2 4 4]
   [0 2 2]
   [3 0 1]]

  [[4 4 2]
   [2 2 1]
   [0 1 3]]

  [[4 2 4]
   [2 1 0]
   [1 3 0]]

  [[2 4 3]
   [1 0 0]
   [3 0 1]]]


 [[[2 1 0]
   [3 3 1]
   [4 3 2]]

  [[1 0 1]
   [3 1 0]
   [3 2 2]]

  [[0 1 0]
   [1 0 3]
   [2 2 2]]

  [[1 0 2]
   [0 3 0]
   [2 2 3]]

  [[0 2 2]
   

67. Consider a 16x16 array, how to get the blocksum
(block size is 4x4)?

In [ ]:
Z = np.ones(16,16)
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
np.arange(0, Z.shape[1], k), axis=1)

68.How to get the n largest values of an array

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


69. Given an arbitrary number of vectors, build the cartesian product (every
combinations of every item).

In [ ]:
def cartesian(arrays):
  arrays = [np.asarray(a) for a in arrays]
  shape = (len(x) for x in arrays)
  ix = np.indices(shape, dtype=int)
  ix = ix.reshape(len(arrays), -1).T
  for n, arr in enumerate(arrays):
    ix[:, n] = arrays[n][ix[:, n]]
  return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


70. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [2]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[1 2 4 5 6 7]


71. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [5]:
nums = np.random.randint(0,4,(10,3))
print("Original vector:")
print(nums)
new_nums = np.logical_and.reduce(nums[:,1:] == nums[:,:-1], axis=1)
result = nums[~new_nums]
print("\nRows with unequal values:")
print(result)

Original vector:
[[0 3 0]
 [2 0 2]
 [3 2 2]
 [2 0 1]
 [3 0 1]
 [2 2 3]
 [1 0 0]
 [0 1 2]
 [2 1 2]
 [0 2 1]]

Rows with unequal values:
[[0 3 0]
 [2 0 2]
 [3 2 2]
 [2 0 1]
 [3 0 1]
 [2 2 3]
 [1 0 0]
 [0 1 2]
 [2 1 2]
 [0 2 1]]


Same code with user define array for better understanding

In [6]:
nums = np.array([(1,1,1),
              (1,1,1),
              (1,2,3)])
print("Original vector:")
print(nums)
new_nums = np.logical_and.reduce(nums[:,1:] == nums[:,:-1], axis=1)
result = nums[~new_nums]
print("\nRows with unequal values:")
print(result)

Original vector:
[[1 1 1]
 [1 1 1]
 [1 2 3]]

Rows with unequal values:
[[1 2 3]]


72. Convert a vector of ints into a matrix binary representation

In [7]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


73. Given a two dimensional array, how to extract unique rows?

In [9]:
data = np.array([[1, 1, 1, 0, 0, 0],
                 [0, 1, 1, 1, 0, 0],
                 [0, 1, 1, 1, 0, 0],
                 [1, 1, 1, 0, 0, 0],
                 [1, 1, 1, 1, 1, 0]])
unique_rows = np.unique(data, axis=0)
print(unique_rows)

[[0 1 1 1 0 0]
 [1 1 1 0 0 0]
 [1 1 1 1 1 0]]
