<a href="https://colab.research.google.com/github/mobilerobotp4/Python/blob/master/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import torch
import torch.nn as nn
import numpy as np
A=array([[5.0,3.5,1.3,0.3,1,0,0],
[4.5,2.3,1.3,0.3,1,0,0],
[4.4,3.2,1.3,0.2,1,0,0],
[5.0,3.5,1.6,0.6,1,0,0],
[5.1,3.8,1.9,0.4,1,0,0],
[4.8,3.0,1.4,0.3,1,0,0],
[5.1,3.8,1.6,0.2,1,0,0],
[4.6,3.2,1.4,0.2,1,0,0],
[5.3,3.7,1.5,0.2,1,0,0],
[5.0,3.3,1.4,0.2,1,0,0],
[5.5,2.6,4.4,1.2,0,1,0]])
print(A[:,:4])
torch.tensor([[1., -1.], [1., -1.]])
model = torch.nn.Sequential(
          nn.Conv2d(1,20,5),
          nn.ReLU(),
          nn.Conv2d(20,64,5),
          nn.ReLU()
        )
#np.arange(3)
arr = np.arange(9).reshape((3, 3))
np.random.shuffle(arr)
#arr
m = nn.Linear(20, 30)
input = torch.randn(128, 20)
output = m(input)
print(output.size())


[[5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [5.5 2.6 4.4 1.2]]
torch.Size([128, 30])
